version: '3.8'

services:
  backend:
    image: chawkimk/backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MeetDB;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - db
  frontend:
    image: chawkimk/clientapp
    container_name: clientapp
    ports:
      - "8080:4200"
    depends_on:
      - backend
   
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
